service: stickers-storage-bot

provider:
  name: aws
  region: ${opt:region, "eu-north-1"}
  runtime: go1.x
  environment:
    TELEGRAM_TOKEN: ${file(./serverless.env.yml):TELEGRAM_TOKEN, ''}
    DYNAMODB_TABLE: ${self:service}-stickers
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:table/*"

resources:
  Resources:
    stickersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: UserID
            AttributeType: N
          - AttributeName: FileUniqueID
            AttributeType: S
        KeySchema:
          - AttributeName: UserID
            KeyType: HASH
          - AttributeName: FileUniqueID
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: FileUniqueIDIndex
            KeySchema:
              - AttributeName: FileUniqueID
                KeyType: HASH
              - AttributeName: UserID
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  webhook:
    handler: bin/webhook
    events:
      - http: POST /

  setWebhook:
    handler: bin/setwebhook
    events:
      - http: POST /set-webhook

package:
  exclude:
    - ./**
  include:
    - ./bin/**
