version: "3.8"

services:
  dynamodb:
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath ./data
    image: amazon/dynamodb-local:1.17.0
    volumes:
      - ./dynamodb:/home/dynamodblocal/data
    working_dir: /home/dynamodblocal
  bot:
    build:
      context: ..
      dockerfile: ./docker/bot/Dockerfile
    env_file:
      - ../.env
    depends_on:
      - dynamodb
